project_name: mach-composer

before:
  hooks:
    - make tidy

builds:
  - id: mach-composer
    main: ./cmd/mach-composer
    binary: bin/mach-composer
    flags:
      - -trimpath
      - -tags=netgo
    env:
      - CGO_ENABLED=0
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -extldflags '-static'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: "{{ .ProjectName }}"
    tap:
      owner: labd
      name: homebrew-{{ .ProjectName }}
    url_template: https://github.com/labd/mach-composer/releases/download/v{{ .Version }}/{{ .ArtifactName }}
    commit_author:
      name: goreleaserbot
      email: opensource@labdigital.nl
    homepage: "https://machcomposer.io/"
    description: "MACH composer is a framework that you use to orchestrate andextend modern digital commerce & experience platforms, based on MACH technologies and cloud native services.."
    license: "MIT"
    dependencies:
      - name: terraform
      - name: git
        type: optional
