$schema: "http://json-schema.org/draft-07/schema#"
description: Main MACH configuration object.
additionalProperties: false
type: object
properties:
  mach_composer:
    $ref: "#/definitions/MachComposerConfig"
  global:
    $ref: "#/definitions/GlobalConfig"
  sites:
    type: array
    items:
      $ref: "#/definitions/SiteConfig"
  components:
    oneOf:
      - type: string
      - type: object
        properties:
          '$ref':
            type: string
      - type: array
        items:
          $ref: "#/definitions/ComponentConfig"

  sops:
    type: object

definitions:
  MachComposerConfig:
    type: object
    required:
      - version
    additionalProperties: false
    properties:
      version:
        type:
          - string
          - number
      variables_file:
        type: string
      cloud:
        $ref: "#/definitions/MachComposerCloud"
      plugins:
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z-]+$":
            type: object
            additionalProperties: false
            properties:
              source:
                type: string
              version:
                type: string

  MachComposerCloud:
    type: object
    required:
      - organization
      - project
    properties:
      organization:
        type: string
      project:
        type: string

  GlobalConfig:
    type: object
    description: Config that is shared across sites.
    additionalProperties: true
    required:
      - environment
      - terraform_config
      - cloud
    properties:
      environment:
        type: string
      terraform_config:
        $ref: "#/definitions/TerraformConfig"
      cloud:
        type: string

  TerraformConfig:
    type: object
    description: Terraform configuration.
    additionalProperties: true
    properties:
      remote_state:
        allOf:
          - type: object
            additionalProperties: true
            required:
              - plugin
            properties:
              plugin:
                type: string
          - $ref: "#/definitions/RemoteState"

  RemoteState:
    type: object
    properties: {}

  SiteConfig:
    type: object
    description: Site definition.
    additionalProperties: true
    required:
      - identifier
    properties:
      identifier:
        type: string
      endpoints:
        type: object
        patternProperties:
          "^[A-Za-z0-9+-]+$":
            oneOf:
              - type: string
              - $ref: "#/definitions/SiteEndpointConfig"
      components:
        type: array
        items:
          $ref: "#/definitions/SiteComponentConfig"

  SiteEndpointConfig:
    type: object
    additionalProperties: true
    properties:
      url:
        type: string
      key:
        type: string
      zone:
        type: string

  SiteComponentConfig:
    type: object
    description: Component configuration.
    additionalProperties: true
    required:
      - name
    properties:
      name:
        type: string
      variables:
        type: object
      secrets:
        type: object
      store_variables:
        description: Commercetools store specific variables (deprecated)
        type: object
      store_secrets:
        description: Commercetools store specific variables (deprecated)
        type: object
      health_check_path:
        type: string

  ComponentConfig:
    type: object
    additionalProperties: true
    required:
      - name
      - source
      - version
    properties:
      name:
        type: string
      source:
        type: string
      version:
        type: string
      integrations:
        type: array
        items:
          type: string
      endpoints:
        $ref: "#/definitions/ComponentEndpointConfig"
      health_check_path:
        type: string
      branch:
        type: string
    description: Component definition.

  ComponentEndpointConfig:
    type: object
    additionalProperties: false
    patternProperties:
      "[a-zA-Z0-9]+":
        type: string
