site_name: MACH composer

# Repository
repo_name: labd/mach-composer
repo_url: https://github.com/labd/mach-composer
# edit_uri: tree/master/docs/src
edit_uri: ""

copyright: 'Copyright &copy; 2020 - Lab Digital B.V.'
docs_dir: src

nav:
- Overview: index.md
- Tutorial:
  - tutorial/intro.md
  - tutorial/step-1-installation.md
  - tutorial/step-2-setup-ct.md
  - AWS:
    - tutorial/aws/step-3-setup-aws-services.md
    - tutorial/aws/step-4-setup-aws-site.md
    - tutorial/aws/step-5-create-component.md
    - tutorial/aws/step-6-create-mach-stack.md
    - tutorial/aws/examples.md
  - Azure:
    - tutorial/azure/step-3-setup-azure.md
    - tutorial/azure/step-4-create-component.md
    - tutorial/azure/step-5-create-mach-stack.md
    - tutorial/azure/manual.md
  - GCP:
    - tutorial/gcp/step-3-setup-gcp.md
- Topics:
  - topics/concepts.md
  - Components:
    - Introduction: topics/components/index.md
    - topics/components/public.md
  - Deployment:
    - Components: topics/deployment/components.md
    - MACH stack: 
      - Overview: topics/deployment/config/index.md
      - topics/deployment/config/aws.md
      - topics/deployment/config/azure.md
      - topics/deployment/config/integrations.md
      - Components: topics/deployment/config/components.md
  - Integrations:
    - topics/integrations/commercetools.md
    - topics/integrations/contentful.md
    - topics/integrations/amplience.md
    - topics/integrations/sentry.md
  - topics/security.md
  - Architecture guidance:
    - Overview: topics/architecture/index.md
    - Terraform: topics/architecture/terraform.md
    - Tenancy: topics/architecture/tenancy.md
  - Development:
    - Workflow: topics/development/workflow.md
    - topics/development/environment.md
- Reference:
  - Overview: reference/index.md
  - Syntax:
    - Overview: reference/syntax/index.md
    - General config: reference/syntax/general_config.md
    - Sites: reference/syntax/sites.md
    - Component definitions: reference/syntax/components.md
  - Components:
    - reference/components/structure.md
    - reference/components/aws.md
    - reference/components/azure.md
  - reference/cli.md
  - reference/changelog.md
- How-to:
  - howto/index.md
  - howto/create-component.md
  - howto/handle-secrets.md
  - howto/encrypt.md
  - Deploy using GitLab: howto/ci/gitlab.md
  - Deploy using GitHub actions: howto/ci/github.md
  - Deploy using Azure DevOps: howto/ci/devops.md


extra_javascript:
  - _js/mermaid.min.js
  - _js/mermaid-init.js

extra_css:
  - _css/custom.css
  - _css/tasklist.css
  - _css/mermaid.css
  - _css/tabbed.css
  - _css/font-awesome.min.css

use_directory_urls: false

theme:
  name: 'material'
  language: 'en'
  logo: '_img/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Catamaran'
    code: 'Roboto Mono'
  features:
    - navigation.tabs

extra:
  social:
    - type: 'link'
      icon: fontawesome/brands/github-alt
      link: 'https://labdigital.nl/'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.tabbed
  - fontawesome_markdown
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
