site_name: MACH composer

# Repository
repo_name: labd/mach-composer
repo_url: https://github.com/labd/mach-composer
# edit_uri: tree/master/docs/src
edit_uri: ""

copyright: 'Copyright &copy; 2020 - Lab Digital B.V.'
docs_dir: src

nav:
- Overview: index.md
- Tutorial:
  - gettingstarted.md
  - Prequisites:
    - prerequisites/index.md
    - AWS: prerequisites/aws.md
    - Azure: prerequisites/azure.md
    - GCP: prerequisites/gcp.md
    - Manual cloud setup:
      - AWS: prerequisites/aws_manual.md
      - Azure: prerequisites/azure_manual.md
- Topics:
  - concepts.md
  - Deployment:
    - Components: deployment/components.md
    - MACH stack: 
      - Overview: deployment/config/index.md
      - deployment/config/aws.md
      - deployment/config/azure.md
      - deployment/config/integrations.md
      - Components: deployment/config/components.md
    - CI/CD: 
      - GitLab: deployment/ci/gitlab.md
      - GitHub actions: deployment/ci/github.md
      - Azure DevOps: deployment/ci/devops.md
  - security.md
  - Architecture guidance:
    - Overview: guidance/index.md
    - Terraform: guidance/terraform.md
    - Tenancy: guidance/tenancy.md
  - Development:
    - Workflow: development/workflow.md
    - development/environment.md
- Reference:
  - Syntax:
    - Overview: syntax/index.md
    - General config: syntax/general_config.md
    - Sites: syntax/sites.md
    - Component definitions: syntax/components.md
  - Components:
    - Introduction: components/index.md
    - components/structure.md
    - components/aws.md
    - components/azure.md
    - components/public.md
  - Integrations:
    - integrations/commercetools.md
    - integrations/contentful.md
    - integrations/amplience.md
    - integrations/sentry.md
  - development/cli.md
  - changelog.md


extra_javascript:
  - _js/mermaid.min.js
  - _js/mermaid-init.js

extra_css:
  - _css/custom.css
  - _css/tasklist.css
  - _css/mermaid.css
  - _css/tabbed.css
  - _css/font-awesome.min.css

use_directory_urls: false

theme:
  name: 'material'
  language: 'en'
  logo: '_img/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Catamaran'
    code: 'Roboto Mono'
  features:
    - navigation.tabs

extra:
  social:
    - type: 'link'
      icon: fontawesome/brands/github-alt
      link: 'https://labdigital.nl/'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.tabbed
  - fontawesome_markdown
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
