name: Create pre release

on:
  pull_request:
    types: [labeled]

jobs:
  goreleaser:
    if: ${{ github.event.label.name == 'prerelease' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Get goreleaser app token
        id: get-app-token
        uses: labd/action-gh-app-token@main
        with:
          app-id: ${{ secrets.MCI_APP_ID }}
          private-key: ${{ secrets.MCI_APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.MCI_APP_INSTALLATION_ID }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'

      - name: Get the next version
        id: next-tag
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: next --p $(git rev-parse --short "$GITHUB_SHA")

      - name: Create release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean -f .goreleaser-beta.yml
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.next-tag.outputs.output }}
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.app-token }}
          GOPATH: ${{ env.GOPATH }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}

      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: mach-composer
          path: dist/*
