name: Generate release pull request

on:
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@4ac62d64b3fb4e396ec632ebecb74626e1c25d46
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
