name: Run Tests

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.18.x]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

      with:
        version: "2022.1"
        install-go: false
        cache-key: ${{ matrix.go-version }}
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... -v ./...
    - name: Build binaries
      uses: goreleaser/goreleaser-action@v2
      with:
        args: build --rm-dist --snapshot
    - name: Upload to codecov
      uses: codecov/codecov-action@v1.0.6
